{% set name = "hexer" %}
{% set version = "1.4.0" %}
{% set sha256 = "886134fcdd75da2c50aa48624de19f5ae09231d5290812ec05f09f50319242cb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/hobu/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 10-missing-includes.patch

build:
  number: 0

requirements:
  build:
    # - {{ compiler('c') }}
    # - {{ compiler('cxx') }}
    - cmake
    - ninja
    - libgdal
    - cairo
  run:
    - libgdal
    - cairo

test:
  commands:
    - test -f $PREFIX/lib/libhexer.so     # [linux]
    - if not exist %LIBRARY_LIB%\\hexer.lib exit 1  # [win]

about:
  home: https://github.com/hobu/hexer
  summary: "LAS and OGR hexagonal density and boundary surface generation"
  license: LGPL 2.1
  license_file: COPYING

extra:
  recipe-maintainers:
  - v-turin
